language: generic
sudo: required
dist: trusty
notifications:
  email: false
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test
matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4.0
    - os: osx
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4.1
    - os: linux
      env:
        - SWIFT_VERSION=4.0
    - os: linux
      env:
        - SWIFT_VERSION=4.1
